name: DisableEnchant
main: LeoWasCoding\disableenchant\Main
version: 1.1.0
api: 5.3.0

commands:
  paintprotect:
    description: Manage protected worlds for painting breaking
    usage: /paintprotect <add|remove|list> [world]
    permission: paintprotect.manage

  itemframeprotect:
    description: Manage protected worlds for item frame protection
    usage: /itemframeprotect <add|remove|list> [world]
    permission: itemframeprotect.manage

permissions:
  paintprotect.manage:
    default: op
  itemframeprotect.manage:
    default: op
