# Worlds where paintings can't be broken
protected-painting-worlds:
  - disabledworld

# Worlds where item frames can't be broken or interacted with
protected-itemframe-worlds:
  - disabledworld
